/* 
Activité : jeu de devinette
*/

// NE PAS MODIFIER OU SUPPRIMER LES LIGNES CI-DESSOUS
// COMPLETEZ LE PROGRAMME UNIQUEMENT APRES LE TODO

console.log("Welcome to the Guessing Game !");

// Cette ligne génère aléatoirement un nombre entre 1 et 100
var solution = Math.floor(Math.random() * 100) + 1;

// Décommentez temporairement cette ligne pour mieux vérifier le programme
//console.log("(La solution est " + solution + ")");

// TODO : complétez le programme

//This variable determines the number of attempts
var attempts = 0;

var comparison = String(" ");

do {
       
        // This is the number that the operator is entering thinking that, it is the solution
        //console.log("You will have " + attempts + " attempts to guess the solution");
        var guess = Number(prompt("You will have " + attempts + " attempts to guess the solution" + "\n" + "Please guess the random number between 1 and 100 generated by the computer?" + " " +comparison));
        
    
        attempts += 1;

        //The entered number is too big
        if (guess > solution)
            {
                comparison = "The number " + guess + " that was entered is too big compare to the solution";
            }
        else if (guess < solution && guess != 0)
            {
                comparison = "The number " + guess + " that was entered is too small compare to the solution";
            }
        else if (guess == solution)
            {
                
                console.log("Congratulations ! The Solution is " + solution + "\n" + "You found the solution after the " + attempts + "th attempt");
                attempts = 6;
            }
        else if (guess < 1 || guess > 100 || guess == 0)
            {
                console.log("Please Make sure the number you entered is between 1 and 100 !");
            }
        else {
            console.log("Please Make sure the number you entered is between 1 and 100 !");
        }
            
} while (attempts !== 6);
if (attempts == 6 && guess != solution)
    {
        console.log ("Sorry ....The solution was " + solution);
    }